# Generated by Django 3.2.2 on 2026-06-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_dniapiconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dniapiconfiguration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
