# Generated by Django 3.2.2 on 2026-06-10 05:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppApiConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='Meta WhatsApp Cloud API', max_length=80, verbose_name='Proveedor')),
                ('phone_number_id', models.CharField(blank=True, default='', help_text='Identificador del número en Meta Business / WhatsApp Cloud API.', max_length=64, verbose_name='ID del número (Phone Number ID)')),
                ('phone_number_display', models.CharField(blank=True, default='', help_text='Ej. 921047681 o +51921047681 (solo referencia en pantalla).', max_length=20, verbose_name='Número visible')),
                ('business_account_id', models.CharField(blank=True, default='', max_length=64, verbose_name='WhatsApp Business Account ID')),
                ('api_base_url', models.CharField(default='https://graph.facebook.com', max_length=200, verbose_name='URL base API')),
                ('api_version', models.CharField(default='v21.0', max_length=20, verbose_name='Versión API')),
                ('api_token', models.CharField(blank=True, default='', max_length=500, verbose_name='Token de acceso')),
                ('api_timeout', models.PositiveSmallIntegerField(default=30, verbose_name='Tiempo de espera (segundos)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='API habilitada')),
                ('notes', models.CharField(blank=True, default='', max_length=500, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Configuración API WhatsApp',
                'verbose_name_plural': 'Configuración API WhatsApp',
                'permissions': (('view_whatsappapiconfiguration', 'Can view Configuración API WhatsApp'), ('change_whatsappapiconfiguration', 'Can change Configuración API WhatsApp')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppBulkMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre / asunto')),
                ('message_body', models.TextField(verbose_name='Mensaje')),
                ('recipient_source', models.CharField(choices=[('manual', 'Lista manual'), ('clients', 'Clientes con teléfono')], default='manual', max_length=20, verbose_name='Destinatarios')),
                ('recipients_text', models.TextField(blank=True, default='', help_text='Un número por línea o separados por coma. Formato Perú: 9 dígitos o 51...', verbose_name='Teléfonos (manual)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sending', 'Enviando'), ('completed', 'Completado'), ('partial', 'Parcial'), ('failed', 'Fallido')], default='draft', max_length=20, verbose_name='Estado')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Total destinatarios')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Enviados')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Fallidos')),
                ('error_log', models.TextField(blank=True, default='', verbose_name='Errores')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('hour', models.TimeField(default=datetime.datetime.now, verbose_name='Hora')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado el')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje masivo WhatsApp',
                'verbose_name_plural': 'Mensajes masivos WhatsApp',
                'ordering': ['-id'],
                'permissions': (('view_whatsappbulkmessage', 'Can view Mensajes masivos WhatsApp'), ('add_whatsappbulkmessage', 'Can add Mensajes masivos WhatsApp'), ('change_whatsappbulkmessage', 'Can change Mensajes masivos WhatsApp'), ('delete_whatsappbulkmessage', 'Can delete Mensajes masivos WhatsApp')),
                'default_permissions': (),
            },
        ),
    ]
