# Generated by Django 3.2.2 on 2026-06-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappbulkmessage',
            name='filter_criteria',
            field=models.TextField(blank=True, default='{}', help_text='JSON con comunidad, deuda, pagadores, ubicación, producto, etc.', verbose_name='Criterios de filtro'),
        ),
        migrations.AlterField(
            model_name='whatsappbulkmessage',
            name='recipient_source',
            field=models.CharField(choices=[('manual', 'Lista manual'), ('clients', 'Todos los clientes con teléfono'), ('filter', 'Filtrar clientes')], default='manual', max_length=20, verbose_name='Destinatarios'),
        ),
    ]
