"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2.2/ref/settings/
"""

from config import db

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load_dotenv(path):
    """Carga .env local (gitignored) sin dependencia extra."""
    if not os.path.isfile(path):
        return
    with open(path, encoding='utf-8') as env_file:
        for raw_line in env_file:
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, _, value = line.partition('=')
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value


_load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2.2/howto/deployment/checklist/

# Desarrollo local: use variables de entorno o valores por defecto (no usar en producción).
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'dev-only-change-me-sv3bn4w^rir+zz4@jh_cse38bi3sxh#3s-3ro@yybzrmk98=bp',
)

DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').strip()
ALLOWED_HOSTS = [h.strip() for h in _hosts.split(',') if h.strip()]

# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'widget_tweaks',
]

LOCAL_APPS = [
    'core.security',
    'core.user',
    'core.login',
    'core.marketing',
    'core.dashboard',
    'core.pos',
    'core.reports',
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'crum.CurrentRequestUserMiddleware'
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.security.functions.system_information',
                'core.security.session_group.auth_group',
                'core.marketing.context_processors.marketing_site',
                'core.marketing.context_processors.marketing_client_portal',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2.2/ref/settings/#databases

DATABASES = db.SQLITE

# Password validation
# https://docs.djangoproject.com/en/3.2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'US/Pacific'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')

MEDIA_URL = '/media/'

# Login

LOGIN_REDIRECT_URL = '/dashboard/'

LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/login/'

# Nombre mostrado en la portada pública (/)
SITE_NAME = os.environ.get('SITE_NAME', 'Empresa')

AUTH_USER_MODEL = 'user.User'

# Email (Gmail: usar contraseña de aplicación en EMAIL_HOST_PASSWORD — ver cuenta Google)

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'seo.cristhian@gmail.com'
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = 'seo.cristhian@gmail.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Formulario de contacto del sitio público (destino)
MARKETING_CONTACT_EMAIL = os.environ.get(
    'MARKETING_CONTACT_EMAIL',
    'terrafirmaperu@gmail.com',
)

# Configurations

LOCALHOST = os.environ.get('DJANGO_PUBLIC_HOST', 'localhost')

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

SESSION_COOKIE_NAME = 'factora'

GROUPS = {
    'client': 2,
}

# API DNI (configurable por variables de entorno)
DNI_API_URL = os.environ.get('DNI_API_URL', 'https://api.decolecta.com/v1/reniec/dni?numero={dni}')
DNI_API_TOKEN = os.environ.get('DNI_API_TOKEN', '')
DNI_API_TIMEOUT = int(os.environ.get('DNI_API_TIMEOUT', '12'))

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
