# Generated by Django 3.2.2 on 2026-04-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=13, unique=True, verbose_name='Dni, RUC ó Cédula'),
        ),
    ]
