# Generated by Django 3.2.2 on 2026-05-09 01:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=20, verbose_name='Estado')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de apertura')),
                ('opening_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto inicial de caja')),
                ('close_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de cierre')),
                ('closing_amount_counted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto contado al cierre')),
                ('closing_amount_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto esperado al cierre')),
                ('difference_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferencia (contado - esperado)')),
                ('observations', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.company', verbose_name='Empresa')),
                ('user_closed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions_closed', to=settings.AUTH_USER_MODEL, verbose_name='Usuario cierre')),
                ('user_opened', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions_opened', to=settings.AUTH_USER_MODEL, verbose_name='Usuario apertura')),
            ],
            options={
                'verbose_name': 'Sesión de caja',
                'verbose_name_plural': 'Sesiones de caja',
                'ordering': ['-opened_at', '-id'],
                'permissions': (('view_cashregistersession', 'Can view Sesión de caja'), ('add_cashregistersession', 'Can add Sesión de caja'), ('change_cashregistersession', 'Can change Sesión de caja'), ('delete_cashregistersession', 'Can delete Sesión de caja')),
                'default_permissions': (),
            },
        ),
    ]
