# Generated by Django 3.2.2 on 2026-05-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_sale_credit_down_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta_debito_credito', 'Tarjeta'), ('efectivo_tarjeta', 'Efectivo y Tarjeta')], default='efectivo', max_length=50),
        ),
    ]
