# Generated by Django 3.2.2 on 2026-05-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_sale_payment_method'),
        ('pos', '0006_sale_payment_cash_register_session'),
    ]

    operations = [
    ]
