# Generated by Django 3.2.2 on 2026-05-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_clientproperty_contract_locked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientproperty',
            options={'ordering': ['order', 'id'], 'permissions': (('unlock_contract_predio', 'Autorizar desvinculación de predios con contrato'),), 'verbose_name': 'Predio del cliente', 'verbose_name_plural': 'Predios del cliente'},
        ),
        migrations.AlterField(
            model_name='advisoryprogresscase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='advisoryprogressstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientproperty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
