# Generated by Django 3.2.2 on 2026-06-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_expenses_cash_register_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolution',
            options={'default_permissions': (), 'ordering': ['-id'], 'permissions': (('view_devolution', 'Can view Cancelaciones'), ('add_devolution', 'Can add Cancelaciones'), ('delete_devolution', 'Can delete Cancelaciones')), 'verbose_name': 'Cancelación', 'verbose_name_plural': 'Cancelaciones'},
        ),
    ]
